# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodFood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "SnapKit", '~> 5.6.0'
  pod 'IQKeyboardManager' ,'6.5.6'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'FSPagerView'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'MJRefresh','3.5.0'  # ,'3.5.0'  <- 3.4.3

  
	
  # Pods for FoodFood

end
